server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/team/**
        - id: comercial-service
          uri: lb://comercial-service
          predicates:
            - Path=/comercial/**
        - id: seguridad-service
          uri: lb://seguridad-service
          predicates:
            - Path=/seguridad/**
